name: Install Cert Manager CRDs on GKE

on:
  workflow_dispatch:
    # inputs:
    #   cluster_name:
    #     description: 'GKE Cluster Name'
    #     required: true
    #     type: string
    #   cluster_zone:
    #     description: 'GKE Cluster Zone'
    #     required: true
    #     type: string
    #   project_id:
    #     description: 'GCP Project ID'
    #     required: true
    #     type: string

env:
  GKE_CLUSTER: juangar-sandbox-gke-cluster
  GKE_ZONE: us-central1
  PROJECT_ID: juangar-sandbox

jobs:
  install-argocd:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      id-token: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
        service_account: ${{ secrets.GKE_SA }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Install gke-gcloud-auth-plugin
      run: |
        gcloud components install gke-gcloud-auth-plugin

    - name: Configure kubectl
      run: |
        gcloud container clusters get-credentials $GKE_CLUSTER --zone $GKE_ZONE --project $PROJECT_ID

    - name: Install Cert Manager CRDs
      run: |
        kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.18.2/cert-manager.yaml