apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: demo-app-secret
  namespace: staging
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets
    kind: ClusterSecretStore
  target:
    name: demo-app-secret
    creationPolicy: Owner
  data:
    - secretKey: apiKey
      remoteRef:
        key: /staging/demo-app/api-key
